name: deploy-project
on: [push, workflow_dispatch]
jobs:
  testy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code babes
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: "Install dependencies honey"
        run: npm ci
      - name: Run some tests
        run: npm test
  deploy:
    needs: testy
    runs-on: ubuntu-latest
    steps:
      - name: Get code girly
        uses: actions/checkout@v3
      - name: Install NodeJS my guy
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: "Install dependencies homie"
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
      
      

